# Generated by Django 4.2.3 on 2023-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
