# Generated by Django 4.2.3 on 2023-09-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'class_information',
                'verbose_name_plural': 'class_information',
                'db_table': 'class_information',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('grade', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'classroom',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='CombinationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'combination_category',
                'verbose_name_plural': 'combination_categories',
                'db_table': 'combination_categories',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('syllabus_code', models.CharField(max_length=5, unique=True)),
                ('syllabus_link', models.URLField(blank=True)),
                ('combination_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classroom.combinationcategory')),
            ],
            options={
                'verbose_name': 'subject',
                'db_table': 'subjects',
            },
        ),
    ]
