# Generated by Django 4.2.3 on 2023-09-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.combinationcategory'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(through='classroom.ClassInformation', to='classroom.subject'),
        ),
        migrations.AddField(
            model_name='classinformation',
            name='class_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='classinformation',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='classinformation',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.subject'),
        ),
    ]
