# Generated by Django 4.2.3 on 2023-09-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentattendance'),
        ('classroom', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=5)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classroom.classroom')),
                ('students', models.ManyToManyField(blank=True, related_name='class_attendance_records', to='student.studentattendance')),
            ],
        ),
    ]
