# Generated by Django 4.2.3 on 2023-09-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classattendance',
            options={'verbose_name': 'class_attendance'},
        ),
        migrations.AlterModelTable(
            name='classattendance',
            table='class_attendancies',
        ),
    ]
