# Generated by Django 4.2.3 on 2023-09-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_classattendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('time', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classroom.subject')),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=5)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='classroom.classroom')),
            ],
            options={
                'verbose_name': 'class_timetable',
                'db_table': 'class_timetables',
            },
        ),
    ]
