# Generated by Django 4.2.3 on 2023-09-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('classroom', '0006_exam_classtimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='day',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='period',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='subject',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='classroom.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classtimetable',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teacher.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='classroom.classroom'),
        ),
    ]
