# Generated by Django 4.2.3 on 2023-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_classtimetable_day_classtimetable_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('threshold', models.CharField(max_length=6)),
                ('fro', models.CharField(max_length=6, verbose_name='From')),
                ('to', models.CharField(max_length=6, verbose_name='To')),
                ('comment', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'db_table': 'grade_book',
            },
        ),
    ]
