# Generated by Django 4.2.3 on 2023-09-30 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('last_name', models.CharField(db_index=True, max_length=40)),
                ('initial', models.CharField(blank=True, max_length=3)),
                ('first_name', models.CharField(max_length=80)),
                ('religion', models.CharField(max_length=90)),
                ('d_o_b', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('id_no', models.CharField(max_length=25, verbose_name='Identification Number')),
                ('profile_pic', models.ImageField(null=True, upload_to='images/avatar/profile')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('identity', models.CharField(choices=[('1', 'Dean'), ('2', 'Deputy'), ('3', 'Hod'), ('4', 'Teacher'), ('5', 'Student'), ('6', 'Admin'), ('7', 'Parent')], max_length=2)),
                ('salary', models.PositiveSmallIntegerField(default=0)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='+263')),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('driver_license', models.CharField(max_length=20, verbose_name='license')),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'verbose_name': 'driver',
                'verbose_name_plural': 'drivers',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=20, verbose_name='route')),
                ('no', models.CharField(max_length=20, verbose_name='Number')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.driver')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicles',
            },
        ),
    ]
