# Generated by Django 4.2.3 on 2023-10-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_parent_identity_alter_student_identity'),
        ('school', '0002_driver_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='identity',
            field=models.CharField(choices=[('1', 'Dean'), ('2', 'Deputy'), ('3', 'Hod'), ('4', 'Teacher'), ('5', 'Student'), ('6', 'Admin'), ('7', 'Parent'), ('8', 'Driver')], max_length=2),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('no', models.CharField(max_length=10, verbose_name='Room Number')),
                ('ty', models.CharField(max_length=10, verbose_name='Room Type')),
                ('n_bed', models.PositiveSmallIntegerField(verbose_name='Number of bed')),
                ('students', models.ManyToManyField(related_name='hostel', to='student.student')),
            ],
            options={
                'verbose_name': 'hostel',
                'verbose_name_plural': 'hostels',
                'db_table': 'hostels',
            },
        ),
    ]
