# Generated by Django 4.2.3 on 2023-09-29 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hod', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now=True)),
                ('due', models.BooleanField(default=False)),
                ('result', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('last_name', models.CharField(db_index=True, max_length=40)),
                ('initial', models.CharField(blank=True, max_length=3)),
                ('first_name', models.CharField(max_length=80)),
                ('religion', models.CharField(max_length=90)),
                ('d_o_b', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('id_no', models.CharField(max_length=25, verbose_name='Identification Number')),
                ('profile_pic', models.ImageField(null=True, upload_to='images/avatar/profile')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('identity', models.CharField(choices=[('1', 'Dean'), ('2', 'Deputy'), ('3', 'Hod'), ('4', 'Teacher'), ('5', 'Student'), ('6', 'Admin'), ('7', 'Parent')], max_length=2)),
                ('salary', models.PositiveSmallIntegerField(default=0)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('assessments', models.ManyToManyField(related_name='teachers', to='teacher.assessment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hod.department')),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('optional_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teachers', to='classroom.subject')),
                ('student_review', models.ManyToManyField(related_name='teachers_reviews', to='student.studentreview')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='classroom.subject')),
                ('teaching_classrooms', models.ManyToManyField(related_name='subject_teachers', to='classroom.classroom')),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
