# Generated by Django 4.2.3 on 2023-10-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identity',
            field=models.CharField(choices=[('1', 'Dean'), ('2', 'Deputy'), ('3', 'Hod'), ('4', 'Teacher'), ('5', 'Student'), ('6', 'Admin'), ('7', 'Parent'), ('8', 'Driver')], max_length=2),
        ),
    ]
