# Generated by Django 4.2.3 on 2023-09-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BooleanField(default=False, verbose_name='Presence')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='student.student')),
            ],
            options={
                'verbose_name': 'students_attendency',
                'verbose_name_plural': 'students_attendencies',
                'db_table': 'students_attendencies',
            },
        ),
    ]
