# Generated by Django 4.2.3 on 2023-09-30 19:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentattendance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='+263'),
        ),
    ]
