# Generated by Django 4.2.3 on 2023-09-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dean', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputy',
            name='optional_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher', verbose_name='Optional_Job'),
        ),
        migrations.AddField(
            model_name='deputy',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.AddField(
            model_name='dean',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='dean',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
