# Generated by Django 4.2.3 on 2023-09-30 19:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dean',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='+263'),
        ),
        migrations.AddField(
            model_name='deputy',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='+263'),
        ),
    ]
